[package]
name = "waves"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "0.9.5", package = "gtk4", features = ["v4_12"] }
epoxy = "0.1.0"
libloading = "0.8.6"
claxon = "0.4.3"
log = "0.4.25"
env_logger = "0.11.6"
lofty = "0.22.2"

[build-dependencies]
glib-build-tools = "0.20.0"